
{
	id:"/API/jQueryExtends/bindTab",
	head:{
		type:"method", 
		name:"bindTab",
		flnm:"jQueryExtends.bindTab",
		file:"_AXJ/lib/AXTab.js",
		tags:"jQueryExtends,bindTab"
	},
	h1:"bindTab",
	desc: "타겟엘리먼트에 원하는 options로 탭을 생성합니다.",
	define: "$(\"jQuerySelector\").bindTab(configs);",
	arguments:[
		{k:"configs", v:{
			theme:"(String) AXTabl CSS 클래스",
			value:"(String) 선택된 options 값",
			overflow:"(<b>\"visible\"</b> | \"scroll\") 탭컨테이너의 너비를 넘어서는 탭의 표현방식 \"scroll\"을 지정하면 컨테이너 너비 안에서 스크롤 처리 됩니다. ",
			scrollAmount:"(Number) overflow : \"scroll\" 의 경우 마우스 오버로 이동하는 탭의 이동량",
			options:"(Array) {optionValue:\"\", optionText:\"\"} 의 배열로 지정합니다. ",
			onchange:"(Function) 선택된 탭이 변경 되었을때 발생되는 이벤트 콜백함수 인자로 (selectedObject, value)를 사용할 수 있고 this.options, this.item, this.index 도 사용가능 "
		}}
	],
	returns: {k:"", v:""},
	samplecode:[
'$("#myTab01").bindTab({',
'	theme : "AXTabs",',
'	value:"",',
'	overflow:"visible",',
'	options:[',
'		{optionValue:"M", optionText:"남성"}, ',
'		{optionValue:"F", optionText:"여성"}, ',
'		{optionValue:"N", optionText:"선택안함"}, ',
'		{optionValue:"", optionText:"모두"}',
'	],',
'	onchange: function(selectedObject, value){',
'		//toast.push(Object.toJSON(this));',
'		//toast.push(Object.toJSON(selectedObject));',
'		toast.push(Object.toJSON(value));',
'	}',
'});'
	],
	example:[
'<div id="myTab01"></div>'
	],
	exampleFn:[
'$("#myTab01").bindTab({',
'	theme : "AXTabs",',
'	value:"",',
'	overflow:"visible",',
'	options:[',
'		{optionValue:"M", optionText:"남성"}, ',
'		{optionValue:"F", optionText:"여성"}, ',
'		{optionValue:"N", optionText:"선택안함"}, ',
'		{optionValue:"", optionText:"모두"}',
'	],',
'	onchange: function(selectedObject, value){',
'		//toast.push(Object.toJSON(this));',
'		//toast.push(Object.toJSON(selectedObject));',
'		toast.push(Object.toJSON(value));',
'	}',
'});'
	],
	reference:[],
	extendForm:[
		{
			description:['overflow:scroll 타입'],
			samplecode:[
'$("#myTab02").bindTab({',
'	theme : "AXTabs",',
'	value:"2",',
'	overflow:"scroll",',
'	scrollAmount:2,',
'	options:[',
'		{optionValue:"1", optionText:"★☆★☆★☆ 1살 선택하기 ★☆★☆★☆"}, ',
'		{optionValue:"2", optionText:"2살 선택하기"}, ',
'		{optionValue:"3", optionText:"3살 선택하기", addClass:"Red"}, ',
'		{optionValue:"4", optionText:"4살 선택하기", addClass:"Blue"}, ',
'		{optionValue:"5", optionText:"5살 선택하기", addClass:"Green"}, ',
'		{optionValue:"6", optionText:"6살 선택하기", addClass:"Classic"}, ',
'		{optionValue:"7", optionText:"7살 선택하기"},',
'		{optionValue:"8", optionText:"8살 선택하기"},',
'		{optionValue:"9", optionText:"9살 선택하기"},',
'		{optionValue:"10", optionText:"★☆★☆★☆ 10살 선택하기 ★☆★☆★☆"},',
'		{optionValue:"11", optionText:"★☆★☆★☆ 11살 선택하기 ★☆★☆★☆"},',
'		{optionValue:"12", optionText:"★☆★☆★☆ 12살 선택하기 ★☆★☆★☆"},',
'		{optionValue:"13", optionText:"13살 선택하기"},',
'		{optionValue:"14", optionText:"14살 선택하기"},',
'		{optionValue:"15", optionText:"15살 선택하기"},',
'		{optionValue:"16", optionText:"16살 선택하기"}',
'	],',
'	onchange: function(selectedObject, value){',
'		//toast.push(Object.toJSON(this));',
'		//toast.push(Object.toJSON(selectedObject));',
'		toast.push(Object.toJSON(value));',
'	}',
'});'
			],
			example: [
'<div id="myTab02"></div>'
			],
			exampleFn: [
'$("#myTab02").bindTab({',
'	theme : "AXTabs",',
'	value:"2",',
'	overflow:"scroll",',
'	scrollAmount:2,',
'	options:[',
'		{optionValue:"1", optionText:"★☆★☆★☆ 1살 선택하기 ★☆★☆★☆"}, ',
'		{optionValue:"2", optionText:"2살 선택하기"}, ',
'		{optionValue:"3", optionText:"3살 선택하기", addClass:"Red"}, ',
'		{optionValue:"4", optionText:"4살 선택하기", addClass:"Blue"}, ',
'		{optionValue:"5", optionText:"5살 선택하기", addClass:"Green"}, ',
'		{optionValue:"6", optionText:"6살 선택하기", addClass:"Classic"}, ',
'		{optionValue:"7", optionText:"7살 선택하기"},',
'		{optionValue:"8", optionText:"8살 선택하기"},',
'		{optionValue:"9", optionText:"9살 선택하기"},',
'		{optionValue:"10", optionText:"★☆★☆★☆ 10살 선택하기 ★☆★☆★☆"},',
'		{optionValue:"11", optionText:"★☆★☆★☆ 11살 선택하기 ★☆★☆★☆"},',
'		{optionValue:"12", optionText:"★☆★☆★☆ 12살 선택하기 ★☆★☆★☆"},',
'		{optionValue:"13", optionText:"13살 선택하기"},',
'		{optionValue:"14", optionText:"14살 선택하기"},',
'		{optionValue:"15", optionText:"15살 선택하기"},',
'		{optionValue:"16", optionText:"16살 선택하기"}',
'	],',
'	onchange: function(selectedObject, value){',
'		//toast.push(Object.toJSON(this));',
'		//toast.push(Object.toJSON(selectedObject));',
'		toast.push(Object.toJSON(value));',
'	}',
'});'
			]
		}
	]
},
{
	id:"/API/jQueryExtends/setValueTab",
	head:{
		type:"method", 
		name:"setValueTab",
		flnm:"jQueryExtends.setValueTab",
		file:"_AXJ/lib/AXTab.js",
		tags:"jQueryExtends,setValueTab"
	},
	h1:"setValueTab",
	desc: "AXTab의 선택값을 변경합니다. ",
	define: "$(\"jQuerySelector\").setValueTab(String);",
	arguments:[
		{k:"String", v:"(String) 선택 값 "}
	],
	returns: {k:"", v:""},
	samplecode:[
'$("#myTab01").bindTab({',
'	theme : "AXTabs",',
'	value:"",',
'	overflow:"visible",',
'	options:[',
'		{optionValue:"M", optionText:"남성"}, ',
'		{optionValue:"F", optionText:"여성"}, ',
'		{optionValue:"N", optionText:"선택안함"}, ',
'		{optionValue:"", optionText:"모두"}',
'	],',
'	onchange: function(selectedObject, value){',
'		//toast.push(Object.toJSON(this));',
'		//toast.push(Object.toJSON(selectedObject));',
'		toast.push(Object.toJSON(value));',
'	}',
'});',
'$("#myTab01").setValueTab("F");'
	],
	example:[
'<div id="myTab01"></div>',
'<p></p>',
'<input type="button" value="탭선택값 강제변경 (여성)" class="AXButton Red" onclick="$(\'#myTab01\').setValueTab(\'F\');" />',
'<input type="button" value="탭선택값 강제변경 (선택안함)" class="AXButton Blue" onclick="$(\'#myTab01\').setValueTab(\'N\');" />'
	],
	exampleFn:[
'$("#myTab01").bindTab({',
'	theme : "AXTabs",',
'	value:"",',
'	overflow:"visible",',
'	options:[',
'		{optionValue:"M", optionText:"남성"}, ',
'		{optionValue:"F", optionText:"여성"}, ',
'		{optionValue:"N", optionText:"선택안함"}, ',
'		{optionValue:"", optionText:"모두"}',
'	],',
'	onchange: function(selectedObject, value){',
'		//toast.push(Object.toJSON(this));',
'		//toast.push(Object.toJSON(selectedObject));',
'		toast.push(Object.toJSON(value));',
'	}',
'});'
	],
	reference:[],
	extendForm:[]
}