
{
	id:"/API/Objects/AXContextMenu",
	head:{
		type:"Objects", 
		name:"AXContextMenu",
		flnm:"Objects.AXContextMenu",
		file:"_AXJ/lib/AXJ.js",
		tags:"Objects,AXContextMenu"
	},
	h1:"AXContextMenu",
	items: [
		{
			name: "bind", 
			type: "method", 
			desc: "AXContextMenu 개체에 메뉴 데이터를 바인딩 합니다.",
			define: "AXContextMenu.bind(configs);",
			arguments: [
				{k:"configs", v:{
					id:"(String) 식별자 ID AXContextMenu 컨트롤을 위한 식별자",
					theme:"(String) 테마 클래스",
					width:"(Number) 컨텍스트메뉴의 너비",
					menu:"(JSObject Array) [{label:String, className:String, onclick:Function}] "
				}}
			],
			returns: {k:"", v:""},
			samplecode:[
'//1레벨 메뉴',
'AXContextMenu.bind({',
'	id:"myContextMenu", ',
'	theme:"AXContextMenu", // 선택항목',
'	width:"150", // 선택항목',
'	menu:[',
'		{userType:0, label:"트리등록", className:"", ',
'		onclick:function(id){',
'			toast.push(Object.toJSON(this));',
'			toast.push(id);',
'		}},',
'		{userType:0, label:"자식트리등록", className:"docline", underLine:true, ',
'		onclick:function(){',
'			toast.push(Object.toJSON(this));',
'		}},',
'		{userType:1, label:"추가하기", className:"plus", onclick:function(){',
'			toast.push(Object.toJSON(this));',
'		}},',
'		{userType:1, label:"수정하기", className:"edit", onclick:function(){',
'			toast.push(Object.toJSON(this));',
'		}},',
'		{userType:1, label:"삭제하기", className:"minus", onclick:function(){',
'			toast.push(Object.toJSON(this));',
'		}}',
'	]',
'});',
'',
'//다차원 레벨 메뉴',
'AXContextMenu.bind({',
'	id:"myContextMenuTree", ',
'	theme:"AXContextMenu", // 선택항목',
'	width:"150", // 선택항목',
'	menu:[',
'		{userType:0, label:"트리등록", onclick:function(id){',
'			toast.push(Object.toJSON(this));',
'			toast.push(id);',
'		}},',
'		{userType:0, label:"하위메뉴 선택", className:"docline", ',
'			onclick:function(){',
'				toast.push(Object.toJSON(this));',
'			}, ',
'			subMenu:[',
'				{userType:0, label:"하위메뉴1", onclick:function(){',
'					toast.push(Object.toJSON(this));',
'				}},',
'				{userType:0, label:"하위메뉴2", onclick:function(){',
'						toast.push(Object.toJSON(this));',
'					}, ',
'					subMenu:[',
'						{userType:0, label:"하위메뉴21", onclick:function(){}},',
'						{userType:0, label:"하위메뉴22", onclick:function(){}}',
'					]',
'				},',
'				{userType:0, label:"하위메뉴3", onclick:function(){}},',
'				{userType:0, label:"하위메뉴3", onclick:function(){}},',
'				{userType:0, label:"하위메뉴3", onclick:function(){}}',
'			],',
'			upperLine:true,',
'			underLine:true',
'		},',
'		{userType:1, label:"추가하기", className:"plus", onclick:function(){',
'			toast.push(Object.toJSON(this));',
'		}},',
'		{userType:1, label:"삭제하기", onclick:function(){',
'			toast.push(Object.toJSON(this));',
'		}}',
'	]',
'});'
			],
			example:[
'<input type="button" value="컨텍스트메뉴 열기" class="AXButton" id="contextBtn1" />'			
			],
			exampleFn:[
'//다차원 레벨 메뉴',
'AXContextMenu.bind({',
'	id:"myContextMenuTree", ',
'	theme:"AXContextMenu", // 선택항목',
'	width:"150", // 선택항목',
'	menu:[',
'		{userType:0, label:"트리등록", onclick:function(id){',
'			toast.push(Object.toJSON(this));',
'			toast.push(id);',
'		}},',
'		{userType:0, label:"하위메뉴 선택", className:"docline", ',
'			onclick:function(){',
'				toast.push(Object.toJSON(this));',
'			}, ',
'			subMenu:[',
'				{userType:0, label:"하위메뉴1", onclick:function(){toast.push(Object.toJSON(this));}},',
'				{userType:0, label:"하위메뉴2", onclick:function(){toast.push(Object.toJSON(this));}, ',
'					subMenu:[',
'						{userType:0, label:"하위메뉴21", onclick:function(){toast.push(Object.toJSON(this));}},',
'						{userType:0, label:"하위메뉴22", onclick:function(){toast.push(Object.toJSON(this));}}',
'					]',
'				},',
'				{userType:0, label:"하위메뉴3", onclick:function(){toast.push(Object.toJSON(this));}},',
'				{userType:0, label:"하위메뉴3", onclick:function(){toast.push(Object.toJSON(this));}},',
'				{userType:0, label:"하위메뉴3", onclick:function(){toast.push(Object.toJSON(this));}}',
'			],',
'			upperLine:true,',
'			underLine:true',
'		},',
'		{userType:1, label:"추가하기", className:"plus", onclick:function(){',
'			toast.push(Object.toJSON(this));',
'		}},',
'		{userType:1, label:"삭제하기", onclick:function(){',
'			toast.push(Object.toJSON(this));',
'		}}',
'	]',
'});',
'',
'$("#contextBtn1").bind("click", function(e){',
'	var event = window.event || e;',
'	AXContextMenu.open({id:"myContextMenuTree", sendObj:{id:"전달하고싶은 오브젝트", name:"형식은 자유"}}, event); // event 직접 연결 방식',
'});'
			],
			reference:	[]
		},
		{
			name:		"open", 
			type:		"method", 
			desc:		"바인드 된 개체를 오픈합니다.",
			define:		"AXContextMenu.open(JSObject);",
			samplecodeDesc:"id, sendObj, event|position 으로 구성된 JSObject를 전달하면 id 로 바인딩 된 AXContextMenu 개체의 오브젝트를 찾아 메뉴를 오픈시켜 줍니다.",
			samplecode:	[
'AXContextMenu.open({',
'	id:"myContextMenuTree", sendObj:{id:"전달하고싶은 오브젝트", name:"형식은 자유"}',
'}, event); // event 직접 연결 방식',
'',
'AXContextMenu.open({',
'	id:"myContextMenuTree", sendObj:{id:"전달하고싶은 오브젝트", name:"형식은 자유"}',
'}, {left:0, top:0}); // position 직접 결정 방식'
			],
			example:[],
			exampleFn:[],
			reference:	[]
		},
		{
			name:		"close", 
			type:		"method", 
			desc:		"바인드 된 개체를 닫습니다.",
			define:		"AXContextMenu.close(JSObject);",
			samplecodeDesc:"id로 구성된 JSObject를 전달하면 id 로 바인딩 된 AXContextMenu 개체의 오브젝트를 찾아 메뉴를 Close시켜 줍니다.",
			samplecode:	[
'AXContextMenu.close({',
'	id:"myContextMenuTree"',
'});'
			],
			example:[],
			exampleFn:[],
			reference:	[]
		}
	]
}
