
{
	id:"/API/Objects/AXConfig",
	head:{
		type:"object", 
		name:"AXConfig",
		flnm:"Objects.AXConfig",
		file:"_AXJ/lib/AXJ.js",
		tags:"Objects,AXConfig"
	},
	h1: "AXConfig",
	desc: "하위 클래스 등에서 사용하는 속성을 정의하는 오브젝트 입니다. ",
	define: [
'var AXConfig = {',
'	weekDays: [',
'		{ label: "일" },',
'		{ label: "월" },',
'		{ label: "화" },',
'		{ label: "수" },',
'		{ label: "목" },',
'		{ label: "금" },',
'		{ label: "토" }',
'	],',
'	AXReq: {',
'		async: true, // AJAX 비동기 처리 여부',
'		okCode: "ok", // 통신 성공 코드',
'		responseType: "", // AJAX responseType',
'		dataType: "", // AJAX return Data type',
'		contentType: "application/x-www-form-urlencoded; charset=UTF-8", // AJAX contentType',
'		dataSendMethod: "parameter", // AJAX parameter send type',
'		crossDomain: false,',
'		resultFormatter: function () { // onsucc formatter',
'			return this;',
'		}',
'	},',
'	AXGrid: {',
'		passiveMode: false,',
'		passiveRemoveHide: false,',
'		fitToWidthRightMargin: 10,',
'		fitToWidth: false,',
'		pageSize: 10,',
'		pageHeight: 400,',
'		keyResult: "result",',
'		keyList: "list",',
'		emptyListMSG: "목록이 없습니다."',
'	},',
'	AXTree: {',
'		fitToWidthRightMargin: 10,',
'		fitToWidth: false,',
'		pageSize: 10,',
'		pageHeight: 400,',
'		keyResult: "result",',
'		keyTree: "tree",',
'		keyList: "list",',
'		emptyListMSG: "목록이 없습니다."',
'	},',
'	AXProgress: {',
'		cancelMsg: "프로세스를 취소 하시겠습니까?"',
'	},',
'	AXUpload5: {',
'		buttonTxt: "Upload files",',
'		deleteConfirm: "정말 삭제하시겠습니까?",',
'		uploadSelectTxt: "업로드 하실 파일을 선택해주세요.",',
'		dropZoneTxt: "업로드할 파일을 여기에 놓습니다."',
'	},',
'	AXModal: {',
'		contentDivClass: "bodyHeightDiv"',
'	},',
'	AXInput: {',
'		errorPrintType: "toast",',
'		selectorOptionEmpty: "목록이 없습니다."',
'	}',
'};'
	],
	samplecodeDesc: "각각의 속성을 변경하는 법 다음은 .net 에서 사용하는 구문 입니다.",
	samplecode:[
		'AXConfig.AXReq.okCode = "00";',
		'AXConfig.AXReq.contentType = "application/json; charset=utf-8";',
		'AXConfig.AXReq.dataSendMethod = "json";',
		'AXConfig.AXReq.resultFormatter = function () {',
		'	return this.d.object();',
		'};'
	],
	example:[],
	exampleFn:[],
	reference:[]
}